### ISSUE TITLE
Read sitemap

### ISSUE THREAD

**Issue by notabene** [notabene/digital-legacy#2]
Hey,

Please read: https://github.com/notabene/digital-legacy/blob/master/workfiles/sitemap.md
(btw generator can be done in a second step, we should first create a static website I think)

Give me a go and I'll start creating a file tree, like this for instance : 

```
pages
  fr
  en
```

**Comment by m4dz** [comment]
Yop! I'm ok with the sitemap, let's go :+1: 

I suggest we use [Hugo](https://gohugo.io) to generate the static website (its support for smartypants an i18n is exactly what we need), so keep the good structure with something like:

```txt
- content
  |- how
  |  |- document.en.md
  |  |- document.fr.md
  |  |- list-of-services.en.md
  |  |- list-of-services.fr.md
  |  |- services
  |  |  |- <one_page_per_service>.{en,fr}.md
  |  |  |- _index.en.md
  |  |  `- _index.fr.md
  |  |- _index.en.md
  |  `- _index.fr.md
  |- testimonials
  |  `- <one_page_per_testimonial>.{en,fr}.md
  |- about
  |  |- _index.en.md
  |  `- _index.fr.md
  |- _index.en.md
  `- _index.fr.md
```

with `_index` files homepages for directories. Does it sound good to you?

About the generator, let's discuss it in another issue, I have several ideas about it, but there's a lot of security stuff about it :steam_locomotive:

**Comment by notabene** [comment]
Cheers. I'll work this week on structure and contents.
